project:
  type: website

website:
  title: sgb-figures
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://stadt-geschichte-basel.github.io/sgb-figures/
  repo-url: https://github.com/stadt-geschichte-basel/sgb-figures/
  issue-url: https://github.com/stadt-geschichte-basel/sgb-figures/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: assets/img/logo_yellow.svg
    logo-alt: ''
    title: sgb-figures
    tools:
      - icon: github
        url: https://github.com/stadt-geschichte-basel/sgb-figures/
        aria-label: GitHub-Repository
    left:
      - text: Plots
        href: index.qmd
      - text: Research Data Platform
        href: https://forschung.stadtgeschichtebasel.ch
      - text: RDM Documentation
        href: https://stadt-geschichte-basel.github.io
      - text: About
        href: index.qmd

  sidebar:
    contents:
      - section: sgb-figures
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Plots)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md

format:
  html:
    link-external-newwindow: true
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    mainfont: Euclid Circular B

freeze: true

editor: visual
