---
title: "Die Bevölkerung von Basel-Stadt, 1912–1966"
subtitle: Plot and Data Preview
date-modified: 2025-09-26
volume: "Arni, Caroline (Hg.): Stadt an der Grenze in einer Zeit der Gefährdung. 1912–1966. Basel 2024 (Stadt.Geschichte.Basel 7)."
vol_short: "Stadt.Geschichte.Basel 7"
plotid: "abb21433"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "21433", "21433_clean.R"))

# Transform Data -------------

data21433_longer <- pivot_longer(data21433,
                                 cols = !Jahr,
                                 names_to = "Bürgerrecht",
                                 values_to = "Anzahl")

data21433_longer$Bürgerrecht <- factor(
  data21433_longer$Bürgerrecht,
  levels = c(
    "Basler Bürgerrecht",
    "Bürgerrecht eines anderen Schweizer Kantons",
    "Ausländische Staatsbürgerschaft"
  )
)

# Plot -----------------------

plot21433 <- ggplot(data = data21433_longer,
                    aes(x = Jahr, y = Anzahl, fill = Bürgerrecht)) +
  
  geom_area(alpha = 1) +
  
  scale_fill_manual(values = c("Ausländische Staatsbürgerschaft" = "#F7CB45",
                               "Basler Bürgerrecht" = "#6195CF",
                               "Bürgerrecht eines anderen Schweizer Kantons" =  "#90C987"),
                    labels = c("Basler Bürgerrecht",
                               "Bürgerrecht eines anderen\nSchweizer Kantons",
                               "Ausländische Staatsbürgerschaft")) +
  
  scale_x_continuous(
    breaks = pretty_breaks(),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 250000),
    breaks = pretty_breaks(),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(legend.position = "none",
        plot.margin = margin(0.5,0.15,0,0.5, "lines"),
        axis.text.y = element_text(margin = margin(r = 5),
                                   hjust = 1),
        legend.key.height = unit(2.5, "mm"), # entspricht 2 mm
        legend.key.width = unit(5, "mm"), # entspricht 4.5 mm
        legend.key.justification = "top") # FIXME works only from Jan25 on, see https://github.com/tidyverse/ggplot2/pull/6279

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot21433 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb21433](https://forschung.stadtgeschichtebasel.ch/items/abb21433.html)",
    "Die Bevölkerung von Basel-Stadt, 1912–1966",
    "Obwohl die Einwohnerschaft mit ausländischer Staatsangehörigkeit in den 1960er-Jahren deutlich zunahm – 1966 lag ihr Anteil bei 15.3 Prozent – blieb sie selbst in absoluten Zahlen unter dem Wert von 1912.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1912/1966",
    "20. Jahrhundert",
    "Arni, Caroline (Hg.): Stadt an der Grenze in einer Zeit der Gefährdung. 1912–1966. Basel 2024 ([Stadt.Geschichte.Basel 7](https://doi.org/10.21255/sgb-07-663402)).",
    "Statistisches Jahrbuch des Kantons Basel-Stadt 1970, S. 21. Daten für das Jahr 1912 aus dem Statistischen Jahrbuch des Kantons Basel Stadt 1921, S. 34. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band7/21433/21433_3_Data.csv-metadata.json](/data/clean/Band7/21433/21433_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Die Bevölkerung von Basel-Stadt, 1912–1966. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb21433.html#m21433_3>, letzte Aktualisierung: 26.09.2025.",
    "2025-09-26 21:43:21"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
