---
title: "Grossratsmandate nach Parteien, 1911–1964"
subtitle: Plot and Data Preview
date-modified: 2025-09-28
volume: "Arni, Caroline (Hg.): Stadt an der Grenze in einer Zeit der Gefährdung. 1912–1966. Basel 2024 (Stadt.Geschichte.Basel 7)."
vol_short: "Stadt.Geschichte.Basel 7"
plotid: "abb22355"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "22355", "22355_clean.R"))

# Transform Data -------------

# Manipulation von 1960 als 1959 und 1964 als 1962, damit gleiche Abstände im Plot erzielt werden
# Label bleibt bei Original-Daten
data22355$Jahr[17] <- 1959
data22355$Jahr[18] <- 1962

data22355_longer <- data22355 %>%
  pivot_longer(cols = -Jahr,
               names_to = "Partei",
               values_to = "Grossratsmandate")

party_colors <- c(
  "Partei der Arbeit" = "#8C2736",
  "Sozialdemokratische Partei" = "#F0554D",
  "Landesring der Unabhängigen" = "#1BAA6E",
  "Vereinigung Evangelischer Wähler" = "#DEAA28",
  "Kath. und Christlich-soziale Volkspartei" = "#D6862B",
  "Radikaldemokratische Partei" = "#3872B5",
  "Liberaldemokratische Bürgerpartei" = "#618DEA",
  "Bürger- und Gewerbepartei" = "#4B8A3E",
  "Andere Parteien" = "#777777"
)

data22355_longer$Partei <- factor(data22355_longer$Partei,
                                  levels = c(
                                    "Partei der Arbeit",
                                    "Sozialdemokratische Partei",
                                    "Landesring der Unabhängigen",
                                    "Vereinigung Evangelischer Wähler",
                                    "Kath. und Christlich-soziale Volkspartei",
                                    "Radikaldemokratische Partei",
                                    "Liberaldemokratische Bürgerpartei",
                                    "Bürger- und Gewerbepartei",
                                    "Andere Parteien"
                                  ))

# Plot -----------------------

plot22355 <- ggplot(data22355_longer,
                    aes(x = Jahr,
                        y = Grossratsmandate,
                        fill = Partei)
                        ) +

  geom_bar(stat = "identity", position = "stack") +
  
  scale_fill_manual(values = party_colors,
                    labels = c("KP und PdA", "SP", "LdU", "EVP und VEW", "KVP", "RDP", "LP und LDP", "BGP und NVP", "Andere")) +
  
  scale_x_continuous(
    breaks = data22355$Jahr,
    labels = c("1911", "1914", "1917", "1920", "1923", "1926", "1929", "1932", "1935", "1938", "1941", "1944", "1947", "1950", "1953", "1956", "1960", "1964"),
    guide = guide_axis(angle = 45),
    expand = expansion(mult = c(0, 0))
  ) +
  
  scale_y_continuous(
    breaks = seq(10, 130, by = 20),
    labels = waiver(),
    expand = expansion(mult = c(0, 0))
  ) +
  
  guides(fill = guide_legend(ncol = 2)) +
  
  coord_cartesian(clip = "off") + 
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    legend.key.width = unit(5, "mm"), # resultiert in 4 mm
    legend.key.height = unit(2.5, "mm"), # resultiert in 2 mm
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    plot.margin = margin(0.5,0.2,0,0, "lines")
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot22355 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Dataset",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb22355 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb22355.html))",
    "Grossratsmandate nach Parteien, 1911–1964",
    "Im frühen 20. Jahrhundert lösten die Sozialdemokraten die zuvor dominierenden Freisinnigen als stärkste Kraft in Basel ab.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1911/1964",
    "20. Jahrhundert",
    "Arni, Caroline (Hg.): Stadt an der Grenze in einer Zeit der Gefährdung. 1912–1966. Basel 2024 ([Stadt.Geschichte.Basel 7](https://doi.org/10.21255/sgb-07-663402)).",
    "[data/clean/Band7/22355/22355_3_Data.csv](/data/clean/Band7/22355/22355_3_Data.csv)",
    "Statistisches Jahrbuch des Kantons Basel-Stadt, diverse Jahrgänge: Daten 1911-1920: Ausgabe 1930. Daten 1923-1941: Ausgabe 1942, S. 195. Daten 1944-1964: Ausgabe 1966, S. 167. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band7/22355/22355_3_Data.csv-metadata.json](/data/clean/Band7/22355/22355_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Grossratsmandate nach Parteien, 1911–1964. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb22355.html#m22355_3>, letzte Aktualisierung: 28.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-28 00:42:07"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (22355_3)")
```
