---
title: "Bürgeraufnahmen und Kriegsausgaben, 1360–1530"
subtitle: Plot and Data Preview
date-modified: 2025-09-26
volume: "Burkart, Lucas (Hg.): Stadt in Verhandlung. 1250–1530. Basel 2024 (Stadt.Geschichte.Basel 3)."
vol_short: "Stadt.Geschichte.Basel 3"
plotid: "abb39492"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)
library(patchwork)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "39492", "39492_clean.R"))

# Plots ----------------------

# vertikale Linien zur besseren Ablesbarkeit
vertical_lines <- seq(1375, 1525, by = 15)

## erster Plot: Kriegsausgaben -----------

plot39492a <- ggplot(data39492, aes(x = Startjahr)) +
  
  geom_vline(xintercept = vertical_lines,
             color = "#777777", linewidth = 0.14,
             linetype = "longdash") +
  
  geom_line(aes(y = `Summe Kriegsausgaben in Pfund`, colour = "Summe Kriegsausgaben in Pfund"),
            linewidth = 0.561) +
  
  scale_colour_manual(values = c("Summe Kriegsausgaben in Pfund" = "#F7CB45"),
                      labels = "Summe Kriegs-\nausgaben in Pfund",
                      drop = FALSE) +
  
  scale_x_continuous(
    breaks = seq(1360, 1525, by = 5),
    labels = everysecond(data39492$Zeitraum),
    guide = guide_axis(angle = 45),
    expand = expansion(mult = c(0, 0))
  ) +

  scale_y_continuous(
    limits = c(0, 40000),
    breaks = pretty_breaks(),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(margin = margin(r = 5),
                                   hjust = 1),
        plot.margin = margin(0.5,0.25,0,0.2, "lines"))

## zweiter Plot: Bürgeraufnahmen -----------

plot39492b <- ggplot(data39492, aes(x = Startjahr)) +
  
  geom_vline(xintercept = vertical_lines,
             color = "#777777", linewidth = 0.14,
             linetype = "longdash") +
  
  geom_line(aes(y = `Summe Bürgeraufnahmen`, colour = "Bürgeraufnahmen"),
            linewidth = 0.561) +
  
  scale_colour_manual(values = c("Bürgeraufnahmen" = "#6195CF"),
                      drop = FALSE) +
  
  scale_x_continuous(
    breaks = seq(1360, 1525, by = 5),
    labels = everysecond(data39492$Zeitraum),
    guide = guide_axis(angle = 45),
    expand = expansion(mult = c(0, 0)),
  ) +

  scale_y_continuous(
    limits = c(0, 1200),
    breaks = seq(0, 1200, by = 300),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(legend.position = "none",
        axis.text.y = element_text(margin = margin(r = 5),
                                   hjust = 1),
        plot.margin = margin(0.5,0.25,0,0.2, "lines"))

# Combine Plots --------------

## Plot 39492a: get legend
plot39492a_with_legend <- plot39492a + theme(legend.position = "right",
                                             legend.justification = c("left", "bottom"))

legende39492a <- get_legend(plot39492a_with_legend) %>%
  as_ggplot()

## Plot 39492b: get legend
plot39492b_with_legend <- plot39492b + theme(legend.position = "right",
                                             legend.justification = c("left", "bottom"))

legende39492b <- get_legend(plot39492b_with_legend) %>%
  as_ggplot()

## Combine Plots with patchwork
plot39492 <- plot39492a + legende39492a + plot39492b + legende39492b + plot_layout(ncol = 2, widths = c(4, 1))

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot39492 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb39492](https://forschung.stadtgeschichtebasel.ch/items/abb39492.html)",
    "Bürgeraufnahmen und Kriegsausgaben, 1360–1530",
    "Der Zusammenhang zwischen Bürgeraufnahmen und Kriegszügen wird aus der Gegenüberstellung mit den städtischen Kriegsausgaben klar ersichtlich. Bis weit ins 15. Jahrhundert richtete sich die Einbürgerungspolitik nach den Bedürfnissen der Stadt im Kriegsfall und nicht nach der Migration. Entsprechend verging wohl für viele Zugezogene eine lange Zeit zwischen Zuwanderung und Einbürgerung (Daten nach: Portmann 1979, S. 96–99. Rosen 1984, S. 477–479)",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1360/1525",
    "Frühe Neuzeit",
    "Burkart, Lucas (Hg.): Stadt in Verhandlung. 1250–1530. Basel 2024 ([Stadt.Geschichte.Basel 3](https://doi.org/10.21255/sgb-03-345800)).",
    "Portmann, Rolf Ernst: Basler Einbürgerungspolitik 1358–1798. Mit einer Berufs- und Herkunftsstatistik des Mittelalters, Basel 1979, S. 96–99. Rosen, Josef: Kriegsausgaben im Spätmittelalter. Der militärische Aufwand in Basel 1360–1535, in: Vierteljahrschrift für Sozial- und Wirtschaftsgeschichte 71, 1984, S. 477–479. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band3/39492/39492_3_Data.csv-metadata.json](/data/clean/Band3/39492/39492_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Bürgeraufnahmen und Kriegsausgaben, 1360–1530. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb39492.html#m39492_3>, letzte Aktualisierung: 26.09.2025.",
    "2025-09-26 21:43:23"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
