---
title: "Der Fahrzeugbestand in Basel-Stadt, 1920–2020"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb77089"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "77089", "77089_clean.R"))

# Transform Data -------------

data77089_Personenwagen <- data77089[,-3:-4]

data77089_Motorräder_inkl_Mofas <- data77089 %>%
  select(Jahr, "Motorräder inkl. Mofas")

data77089_Fahrräder <- data77089 %>%
  select(Jahr, "Fahrräder") %>%
  na.omit()

# Plot -----------------------

plot77089 <- ggplot() +
  
  geom_line(data = data77089_Personenwagen, aes(x = Jahr, y = Personenwagen, color = "Personenwagen"),
            linewidth = 0.561) +
  
  geom_line(data = data77089_Motorräder_inkl_Mofas, aes(x = Jahr, y = `Motorräder inkl. Mofas`,
                                                        color = "Motorräder inkl. Mofas"),
            linewidth = 0.561) +
  
  geom_line(data = data77089_Fahrräder, aes(x = Jahr, y = Fahrräder,
                                            color = "Fahrräder"),
            linewidth = 0.561) +
  
  scale_x_continuous(
    breaks = pretty_breaks(),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 90000),
    breaks = c(0, 30000, 60000, 90000),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_color_manual(values = c("Personenwagen" = "#6195CF",
                                "Motorräder inkl. Mofas" = "#F7CB45",
                                "Fahrräder" = "#bc5231")) +

  coord_cartesian(clip = "off") + 
  
  guides(color = guide_legend(keyheight = unit(4.8, "mm"))) + # results in ca. 3mm
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    legend.key.height = unit(1.64, "mm"),
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    plot.margin = margin(0.5,0.9,0,0, "lines")
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot77089 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Dataset",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb77089 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb77089.html))",
    "Der Fahrzeugbestand in Basel-Stadt, 1920–2020",
    "Die Motorisierung der Gesellschaft machte sich in den 1960er-Jahren eindrücklich bemerkbar: Der Bestand an Autos nahm in Basel massiv zu, während immer weniger Fahrräder im Einsatz waren. Mitte der 1970er-Jahre wuchs der Bestand an Fahrrädern wieder, ab 1990 wurde er nicht mehr erhoben. Anhaltende Popularität hatte das Auto: Der vermeintliche Einbruch um 1980 geht auf eine neue Zählweise zurück. Hinweis: Die Zahlen entsprechen dem Bestand der Motorfahrzeugkontrolle des Kantons Basel-Stadt. Daten aus dem Statistischen Jahrbuch der Schweiz unterscheiden sich jeweils leicht von den Daten im StAJB BS (vermutlich weil jeweils Bestand 'Ende September 19xx)'.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1920/2022",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "https://statistik.bs.ch/apps/jahrbuch; https://statistik.bs.ch/files/webtabellen/t11-1-01.xlsx. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/77089/77089_3_Data.csv](/data/clean/Band8/77089/77089_3_Data.csv)",
    "[data/clean/Band8/77089/77089_3_Data.csv-metadata.json](/data/clean/Band8/77089/77089_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Der Fahrzeugbestand in Basel-Stadt, 1920–2020. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb77089.html#m77089_3>, letzte Aktualisierung: 27.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-27 18:16:59"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (77089_3)")
```
