---
title: "Bevölkerungsentwicklung in den Kantonen Basel-Stadt und Basel-Landschaft, 1940–2020"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb77733"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "77733", "77733_clean.R"))

# Transform Data -------------

colnames(data77733)[3] <- "Wohnbevölkerung Kanton Basel-Landschaft\n(ab 1994 mit Laufental)"

# Plot -----------------------

plot77733 <- ggplot() +
  
  geom_line(data = data77733, aes(x = Jahr, y = `Wohnbevölkerung Kanton Basel-Landschaft\n(ab 1994 mit Laufental)`,
                                                        color = "Wohnbevölkerung Kanton Basel-Landschaft\n(ab 1994 mit Laufental)"),
            linewidth = 0.561) +
  
  geom_line(data = data77733, aes(x = Jahr, y = `Wohnbevölkerung Kanton Basel-Stadt`,
                                  color = "Wohnbevölkerung Kanton Basel-Stadt"),
            linewidth = 0.561) +

  scale_x_continuous(
    breaks = pretty_breaks(),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 300000),
    breaks = seq(0, 300000, 50000),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_color_manual(values = c("Wohnbevölkerung Kanton Basel-Stadt" = "#1d1d1d",
                                "Wohnbevölkerung Kanton Basel-Landschaft\n(ab 1994 mit Laufental)" = "#DC050C"),
                     breaks = c("Wohnbevölkerung Kanton Basel-Stadt",
                                "Wohnbevölkerung Kanton Basel-Landschaft\n(ab 1994 mit Laufental)")) +

  coord_cartesian(clip = "off") + 
  
  guides(color = guide_legend(keyheight = unit(4.8, "mm"))) + # results in ca. 3 mm
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    legend.key.height = unit(1.64, "mm"),
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    plot.margin = margin(0.5,0.9,0,0, "lines")
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot77733 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Dataset",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb77733 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb77733.html))",
    "Bevölkerungsentwicklung in den Kantonen Basel-Stadt und Basel-Landschaft, 1940–2020",
    "Während der Kanton Basel-Stadt nach 1970 einen markanten Rückgang verzeichnete, nahm die Bevölkerung in Basel-Landschaft kontinuierlich zu. Viele junge Familien zog es in die Agglomeration, wo der Traum vom Eigenheim noch finanzierbar war. Die Entwicklung der Wohnbevölkerung veranschaulicht den Trend der Stadtflucht, der im 21. Jahrhundert abflaute.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1940/2020",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "Statistisches Jahrbuch des Kantons Basel-Stadt, diverse Jahrgänge. Moll, Christa; Sandtner, Martin; Saner, Dorothea: Zahlenmeer – mehr als Zahlen. Basel-Stadt – 100 Jahre statistisch begleitet, Basel 2002, Anhang 2.1. https://statistik.bl.ch/web_portal/1_9. https://statistik.bl.ch/web_portal/1_1_3?sheet=6&Jahr=34. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/77733/77733_3_Data.csv](/data/clean/Band8/77733/77733_3_Data.csv)",
    "[data/clean/Band8/77733/77733_3_Data.csv-metadata.json](/data/clean/Band8/77733/77733_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Bevölkerungsentwicklung in den Kantonen Basel-Stadt und Basel-Landschaft, 1940–2020. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb77733.html#m77733_3>, letzte Aktualisierung: 27.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-27 18:16:59"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (77733_3)")
```
