---
title: "Vertretung Basel-Stadt im Ständerat, 1963–2023"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb80238_10"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))

# Read Data ------------------

source(here("src", "80238", "80238d_clean.R"))

# Transform Data -------------

data80238d_longer <- data80238d %>%
  pivot_longer(cols = -Jahr,
               names_to = "Partei",
               values_to = "Ständeratssitze",
               names_prefix = "'",
               names_transform = list(Jahr = as.numeric)) %>%
  mutate(Jahr = gsub("'", "", Jahr)) %>%
  mutate(Jahr = as.numeric(Jahr))

# Plot -----------------------

plot80238d <- ggplot(data80238d_longer,
                    aes(x = Jahr,
                        y = Ständeratssitze,
                        fill = factor(Partei, levels = c("SP",
                                                         "FDP")))) +
                      
  geom_bar(stat = "identity", position = "stack") +
  
  scale_x_continuous(
    breaks = seq(1963, 2019, 4) - 1.8,
    labels = seq(1963, 2019, 4),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 1),
    breaks = c(0, 1),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_fill_manual(values = c("SP" = "#F0554D",
                               "FDP" = "#3872B5")) +
  
  guides(color = guide_legend(keyheight = unit(4.8, "mm"), # results in ca. 3mm
                              ncol = 1)) +
  
  coord_cartesian(clip = "off") + 
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    legend.key.width = unit(5, "mm"), # resultiert in 4 mm
    legend.key.height = unit(2.5, "mm"), # resultiert in 2 mm
    plot.margin = margin(0.5,0.9,0,0.4, "lines"),
    axis.ticks = element_blank(),
    axis.text.y = element_text(margin = margin(r = 5)),
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot80238d + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb80238](https://forschung.stadtgeschichtebasel.ch/items/abb80238.html)",
    "Vertretung Basel-Stadt im Ständerat, 1963–2023",
    "Als Halbkanton steht Basel-Stadt nur ein Sitz im Ständerat zu. Nach dem Freisinnigen Eugen Dietschi (1960–1967) trugen dieses Amt über Jahrzehnte nur noch Vertreterinnen und Vertreter der SP: Willi Wenk (1967–1979), Carl Miville (1979–1991), Gian-Reto Plattner (1991–2003), Anita Fetz (2003–2019), Eva Herzog (seit 2019)",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1963/2019",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "Kanton Basel-Stadt: nationale und kantonale Wahlen seit 1919, Bundesamt für Statistik, je-d-17.02.01_12BS, online: https://www.bfs.admin.ch/bfs/de/home/statistiken/kataloge-datenbanken/tabellen.assetdetail.14836245.html. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/80238/80238_12_Data.csv-metadata.json](/data/clean/Band8/80238/80238_12_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Vertretung Basel-Stadt im Ständerat, 1963–2023. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb80238.html#m80238_12>, letzte Aktualisierung: 27.09.2025.",
    "2025-09-27 01:08:05"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
