---
title: "Grosser Rat in Basel-Stadt, 1960–2024"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb80238_4"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "80238", "80238b_clean.R"))

# Transform Data -------------

data80238b <- data80238b[,-18]

colnames(data80238b)[5] <- "GB (Grünes Bündnis aus\nGrüne & BastA, ab 2021 GAB)"
colnames(data80238b)[11] <- "CVP (ab 2021 Die Mitte)"
colnames(data80238b)[12] <- "EVP (bis 2006 VEW)"
colnames(data80238b)[13] <- "FDP (bis 1973 RDP)"
colnames(data80238b)[16] <- "NA (ab 1991 UVP, ab 1992 SD)"

data80238b_longer <- data80238b %>%
  pivot_longer(cols = -Jahr,
               names_to = "Partei",
               values_to = "Grossratssitze",
               names_prefix = "'",
               names_transform = list(Jahr = as.numeric)) %>%
  mutate(Jahr = gsub("'", "", Jahr)) %>%
  mutate(Jahr = as.numeric(Jahr))

# Plot -----------------------

plot80238b <- ggplot(data80238b_longer,
                    aes(x = Jahr,
                        y = Grossratssitze,
                        fill = factor(Partei, levels = c("POB",
                                                         "FraB",
                                                         "PdA",
                                                         "GB (Grünes Bündnis aus\nGrüne & BastA, ab 2021 GAB)",
                                                         "GP",
                                                         "SP",
                                                         "LdU",
                                                         "GLP",
                                                         "DSP",
                                                         "CVP (ab 2021 Die Mitte)",
                                                         "EVP (bis 2006 VEW)",
                                                         "FDP (bis 1973 RDP)",
                                                         "LDP",
                                                         "SVP",
                                                         "NA (ab 1991 UVP, ab 1992 SD)",
                                                         "Andere")))) +
  
  geom_bar(stat = "identity", position = "stack") +
  
  scale_x_continuous(
    breaks = seq(1960, 2020, 4) - 1.8,  # shift breaks to the left edge of bars
    labels = seq(1960, 2020, 4),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 130),
    breaks = seq(10, 130, 10),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_fill_manual(values = c("POB" = "#88519C",
                               "FraB" = "#8C2736",
                               "PdA" = "#BF3939",
                               "GB (Grünes Bündnis aus\nGrüne & BastA, ab 2021 GAB)" = "#84B547",
                               "GP" = "#487F5A",
                               "SP" = "#F0554D",
                               "LdU" = "#1BAA6E",
                               "GLP" = "#C4C43D",
                               "DSP" = "#BF3939",
                               "CVP (ab 2021 Die Mitte)" = "#D6862B",
                               "EVP (bis 2006 VEW)" = "#DEAA28",
                               "FDP (bis 1973 RDP)" = "#3872B5",
                               "LDP" = "#618DEA",
                               "SVP" = "#4B8A3E",
                               "NA (ab 1991 UVP, ab 1992 SD)" = "#5A3827",
                               "Andere" = "#B8B8B8")) +
  
  guides(color = guide_legend(keyheight = unit(4.8, "mm"), # results in ca. 3mm
                              ncol = 1)) +

  coord_cartesian(clip = "off") + 
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    legend.key.width = unit(5, "mm"), # resultiert in 4 mm
    legend.key.height = unit(2.5, "mm"), # resultiert in 2 mm
    axis.text.y = element_text(margin = margin(r = 5)),
    plot.margin = margin(0.5,0.1,0,0.5, "lines"),
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot80238b + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Dataset",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb80238 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb80238.html))",
    "Grosser Rat in Basel-Stadt, 1960–2024",
    "Die Parteienlandschaft in Basel hat sich seit 1960 stark verändert, mit Auswirkungen auf die Sitzverteilung im Basler Grossrat. Besonders stark waren die­ Umwälzungen in den 1990er-Jahren: Traditionsreiche Parteien wie die PdA und die LdU verloren ihre letzten Sitze, aufstrebende Parteien wie die Grünen und die SVP gewannen in kurzer Zeit viele Mandate. 2005 nahm das Stimmvolk die neue Kantonsverfassung an, eine gewichtige Folge davon war die Verkleinerung des Grossen Rates auf hundert Mitglieder.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1960/2024",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "Sitzverteilung im Grossen Rat seit 1905, Entwicklung Frauenanteil im Grossen Rat, t17.3.05, Statistisches Amt BS, online: https://grosserrat.bs.ch/parlament/ratsgeschichte/entwicklung-der-parteien; Parteien, Jungeparteien und Listenvereinigungen seit 1971, t17.1.01, Statistisches Amt BS, online: https://grosserrat.bs.ch/parlament/ratsgeschichte/entwicklung-der-parteien; Nationale und kantonale Wahlen seit 1919, Bundesamt für Statistik, je-d-17.02.01_12BS, online: https://www.bfs.admin.ch/bfs/de/home/statistiken/kataloge-datenbanken/tabellen.assetdetail.14836245.html. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/80238/80238_6_Data.csv](/data/clean/Band8/80238/80238_6_Data.csv)",
    "[data/clean/Band8/80238/80238_6_Data.csv-metadata.json](/data/clean/Band8/80238/80238_6_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Grosser Rat in Basel-Stadt, 1960–2024. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb80238.html#m80238_6>, letzte Aktualisierung: 27.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-27 18:16:59"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (80238_6)")
```
