---
title: "Leerstandsquote, 1960–2020"
subtitle: Plot and Data Preview
date-modified: 2025-09-26
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb85061"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "85061", "85061_clean.R"))

# Transform Data -------------

data85061 <- data85061 %>%
  mutate(across(.cols = Leerstandsquote, .fns = ~ . / 100))

# Plot -----------------------

plot85061 <- ggplot() +
  
  geom_segment(aes(x = data85061$Jahr, xend = data85061$Jahr,
                   y = 0, yend = data85061$Leerstandsquote),
               color = "#777777",
               linewidth = 0.561) +
  
  geom_point(aes(x = data85061$Jahr,
                 y = data85061$Leerstandsquote,
             color = "Leerstandsquote\nin Prozent"),
             size = 2) +

  scale_x_continuous(
    breaks = pretty_breaks(),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 0.025),
    breaks = pretty_breaks(),
    expand = expansion(mult = c(0, 0)),
    labels = percent_format()
  ) +
  
  scale_color_manual(values = c("Leerstandsquote\nin Prozent" = "#F7CB45")) +
  
  coord_cartesian(clip = "off") + 
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    plot.margin = margin(0.5,0.9,0,0.5, "lines")
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot85061 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb85061](https://forschung.stadtgeschichtebasel.ch/items/abb85061.html)",
    "Leerstandsquote, 1960–2020",
    "Insbesondere in der Hochkonjunktur der 1960er-Jahre, als die Zahl der Einwohnerinnen und Einwohner stark wuchs, war die Wohnungsnot gross. In den 1970er-Jahren entspannte sich die Situation auf dem Wohnungsmarkt. In den 2010er-Jahren machte sich die wachsende Wohnbevölkerung erneut anhand der wenigen freien Wohnungen bemerkbar",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1960/2020",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "Statistisches Amt Kanton Basel-Stadt. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/85061/85061_3_Data.csv-metadata.json](/data/clean/Band8/85061/85061_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Leerstandsquote, 1960–2020. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb85061.html#m85061_3>, letzte Aktualisierung: 26.09.2025.",
    "2025-09-26 21:43:25"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
