---
title: "Religionszugehörigkeiten in Basel-Stadt, 1950–2020"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 (Stadt.Geschichte.Basel 8)."
vol_short: "Stadt.Geschichte.Basel 8"
plotid: "abb86088"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "86088", "86088_clean.R"))

# Transform Data -------------

data86088_longer <- data86088 %>%
  pivot_longer(cols = -Jahr,
               names_to = "Konfession",
               values_to = "Anzahl",
               names_prefix = "'",
               names_transform = list(Jahr = as.numeric)) %>%
  mutate(Jahr = gsub("'", "", Jahr)) %>%
  mutate(Jahr = as.numeric(Jahr))

# Plot -----------------------

plot86088 <- ggplot(data86088_longer, aes(x = Jahr, y = Anzahl,
                                          fill = factor(Konfession, levels = c("Evangelisch-reformiert",
                                                                               "Römisch-katholisch",
                                                                               "Andere christliche Glaubensgemeinschaften",
                                                                               "Jüdische Glaubensgemeinschaften",
                                                                               "Islamische Glaubensgemeinschaften",
                                                                               "Andere Religionsgemeinschaften",
                                                                               "Konfessionslos",
                                                                               "Ohne Angabe")))) +
  
  geom_bar(stat = "identity",
           position = position_dodge()) +
  
  geom_vline(xintercept = seq(1955, 2015, 10),
             color = "#777777",
             linetype = "longdash",
             linewidth = 0.3) +

  scale_x_continuous(
    breaks = seq(1950, 2020, 10),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +
  
  scale_y_continuous(
    limits = c(0, 160000),
    breaks = seq(0, 160000, 20000),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_fill_manual(values = c("Evangelisch-reformiert" = "#6195CF",
                               "Römisch-katholisch" = "#F7CB45",
                               "Andere christliche Glaubensgemeinschaften" = "#EE8026",
                               "Jüdische Glaubensgemeinschaften" = "#F7F056", # was: 90C987
                               "Islamische Glaubensgemeinschaften" = "darkgreen",
                               "Andere Religionsgemeinschaften" = "#882E72",
                               "Konfessionslos" = "#777777",
                               "Ohne Angabe" = "#D1BBD7")) +
  
  coord_cartesian(clip = "off") + 
  
  theme_sgb_basis() +
  theme(
    legend.position = "none",
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    legend.key.height = unit(2.05, "mm"), # entspricht 1.64mm
    legend.key.width = unit(5, "mm"), # entspricht 4mm
    plot.margin = margin(0.5,0.9,0,0.4, "lines"))

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot86088 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Dataset",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb86088 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb86088.html))",
    "Religionszugehörigkeiten in Basel-Stadt, 1950–2020",
    "In den 1950er-Jahren waren fast alle Bewohnerinnen und Bewohner von Basel reformiert oder katholisch, kaum jemand konfessionslos und nur wenige Angehörige einer anderen Glaubensgemeinschaft. Das hat sich seither grundlegend verändert. Basel entwickelte sich zu einer multireligiösen Gesellschaft. Der muslimische Glaube etablierte sich, das Christentum verlor derweil an Bedeutung im Alltag. Keine andere Stadt in der Schweiz hatte um 2020 so viele Konfessionslose wie Basel.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1950/2020",
    "20. Jahrhundert",
    "Lengwiler, Martin (Hg.): Auf dem Weg ins Jetzt. Seit 1960. Basel 2025 ([Stadt.Geschichte.Basel 8](https://doi.org/10.21255/sgb-08-796384)).",
    "Statistisches Amt des Kantons Basel-Stadt. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band8/86088/86088_3_Data.csv](/data/clean/Band8/86088/86088_3_Data.csv)",
    "[data/clean/Band8/86088/86088_3_Data.csv-metadata.json](/data/clean/Band8/86088/86088_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Religionszugehörigkeiten in Basel-Stadt, 1950–2020. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb86088.html#m86088_3>, letzte Aktualisierung: 27.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-27 18:17:01"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (86088_3)")
```
