---
title: "Erwerbstätige nach sozialen Klassen im St. Alban und Klybeck"
subtitle: Plot and Data Preview
date-modified: 2025-09-26
volume: "Kury, Patrick (Hg.): Die beschleunigte Stadt. 1856–1914. Basel 2024 (Stadt.Geschichte.Basel 6)."
vol_short: "Stadt.Geschichte.Basel 6"
plotid: "abb90383"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "90383", "90383_clean.R"))

# Transform Data -------------

data90383$Stadtviertel[1] <- "St. Alban"

data90383_longer <- data90383 %>%
  pivot_longer(
    cols = -Stadtviertel,
    names_to = "Klasse",
    values_to = "Anzahl"
  )

# Diagramm plotten -----------

plot90383 <- ggplot(data = data90383_longer,
                    aes(x = Anzahl, y = Stadtviertel, fill = Klasse)) +
  
  geom_bar(stat = "identity", position = position_fill()) +
  
  scale_fill_manual(values = c("Klasse1" = "#A5170E",
                               "Klasse2" = "#F7F056",
                               "Klasse3" = "#F7CB45",
                               "Klasse4" = "#7BAFDE",
                               "Klasse5" = "#6195CF",
                               "Klasse6" = "#90C987"),
                    labels = c("Klasse1" = "Inhaber und Leiter von Grossbetrieben, hohe Beamte,\nProfessoren, Geistliche, selbstständige Ärzte, Apotheker,\nTierärzte, Anwälte, Ingenieure, Architekten, hervorragende Künstler, Grossrentner",
                               "Klasse2" = "Mittlere und kleine Selbstständige",
                               "Klasse3" = "Mittlere Beamte und Lehrer",
                               "Klasse4" = "Unterbeamte und gelernte Arbeiter",
                               "Klasse5" = "Ungelernte Arbeiter",
                               "Klasse6" = "Häusliche Dienstboten")) +
  
  scale_x_continuous(
    breaks = pretty_breaks(),
    expand = expansion(mult = c(0, 0)),
    labels = label_percent()
  ) +
  
  scale_y_discrete(
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0))
  ) +

  guides(fill = guide_legend(reverse = TRUE)) +
  
  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(legend.position = "none",
        legend.key.height = unit(2.5, "mm"), # entspricht 2 mm
        legend.key.width = unit(5, "mm"), # entspricht 4.5 mm
        axis.text.y = element_text(margin = margin(r = 5),
                                   hjust = 1),
        axis.ticks.y = element_blank(),
        plot.margin = margin(0.1,1.5,0,0.5, "lines"),
        panel.grid.major.x = element_line(color = "black", linewidth = 0.14)
  )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot90383 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb90383](https://forschung.stadtgeschichtebasel.ch/items/abb90383.html)",
    "Erwerbstätige nach sozialen Klassen im St. Alban und Klybeck",
    "Um die soziale Zusammensetzung der Wohnviertel zu bestimmen, teilte die Volkszählung von 1910 die Bevölkerung in «Erwerbstätige nach sozialen Klassen» ein. Während im Alban-Viertel die obersten drei sozialen Klassen mehr als ein Drittel ausmachten, waren es im Klybeck knapp ein Fünftel, dafür ungleich mehr gelernte und ungelernte Arbeiter. Obschon die Dienstboten im Alban-Viertel die Anzahl hoher Beamter und Leiter von Grossbetrieben deutlich übertrafen, wurden sie für die Charakterisierung der Stadtteile nicht miteinbezogen: Für die Prägung eines Stadtteils waren sie in den Augen der Statistiker keine relevante Grösse",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1910",
    "20. Jahrhundert",
    "Kury, Patrick (Hg.): Die beschleunigte Stadt. 1856–1914. Basel 2024 ([Stadt.Geschichte.Basel 6](https://doi.org/10.21255/sgb-06-810743)).",
    "Jenny, Oskar Hugo: Die Bevölkerung des Kantons Basel-Stadt. Am 1. Dezember 1910, Basel 1924 (Mitteilungen des Statistischen Amtes des Kantons Basel-Stadt Nr. 28, Ed. 1924), S. 156f. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band6/90383/90383_3_Data.csv-metadata.json](/data/clean/Band6/90383/90383_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Erwerbstätige nach sozialen Klassen im St. Alban und Klybeck. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb90383.html#m90383_3>, letzte Aktualisierung: 26.09.2025.",
    "2025-09-26 21:43:26"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
