---
title: "Bevölkerungsentwicklung des Kantons Basel-Stadt, 1870–1910"
subtitle: Plot and Data Preview
date-modified: 2025-09-27
volume: "Kury, Patrick (Hg.): Die beschleunigte Stadt. 1856–1914. Basel 2024 (Stadt.Geschichte.Basel 6)."
vol_short: "Stadt.Geschichte.Basel 6"
plotid: "abb92209"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "92209", "92209_clean.R"))

data92209 <- data92209[,-5]

# Transform Data -------------

data92209_longer <- pivot_longer(data92209,
                                 cols = !Jahr,
                                 names_to = "Bürgerrecht",
                                 values_to = "Anzahl")

# Diagramm plotten -----------

plot92209 <- ggplot(data = data92209_longer,
                    aes(x = Jahr, y = Anzahl, fill = Bürgerrecht)) +
  
  geom_area(alpha = 1) +
  
  scale_fill_manual(values = c("#6195CF", "#90C987", "#F7CB45"),
                    labels = c("Ausländische Staatsbürgerschaft",
                               "Basler Bürgerrecht",
                               "Bürgerrecht eines anderen\nSchweizer Kantons")) +
  
  scale_x_continuous(
    breaks = pretty_breaks(),
    guide = guide_axis(),
    expand = expansion(mult = c(0, 0.005))
  ) +

  scale_y_continuous(
    limits = c(0, 140000),
    breaks = pretty_breaks(),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(legend.position = "none",
        plot.margin = margin(0.5,1,0,0.5, "lines"),
        axis.text.y = element_text(margin = margin(r = 5),
                                   hjust = 1),
        legend.key.height = unit(2.5, "mm"), # entspricht 2 mm
        legend.key.width = unit(5, "mm"), # entspricht 4.5 mm
        legend.key.justification = "top") # FIXME works only from Jan25 on, see https://github.com/tidyverse/ggplot2/pull/6279


```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot92209 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Creator",
    "Contributors",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Dataset",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Rights",
    "License",
    "Modified"
  ),
  Value = c(
    "abb92209 ([Research Data Platform](https://forschung.stadtgeschichtebasel.ch/items/abb92209.html))",
    "Bevölkerungsentwicklung des Kantons Basel-Stadt, 1870–1910",
    "Dank der liberalen Einbürgerungspraxis stieg der Anteil der Menschen mit Basler Bürgerrecht von 1900 bis 1910 von rund 17 000 auf 45 000 Personen an. Der Anteil von Einwohner:innen mit ausländischer Staatsbürgerschaft lag um 1910 bei rund 38 Prozent.",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "Nico Görlich, Moritz Twente",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "1870/1910",
    "19. Jahrhundert",
    "Kury, Patrick (Hg.): Die beschleunigte Stadt. 1856–1914. Basel 2024 ([Stadt.Geschichte.Basel 6](https://doi.org/10.21255/sgb-06-810743)).",
    "Mitteilungen des Statistischen Amtes Basel-Stadt, Nr. 28, Basel 1924. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band6/92209/92209_3_Data.csv](/data/clean/Band6/92209/92209_3_Data.csv)",
    "[data/clean/Band6/92209/92209_3_Data.csv-metadata.json](/data/clean/Band6/92209/92209_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Bevölkerungsentwicklung des Kantons Basel-Stadt, 1870–1910. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb92209.html#m92209_3>, letzte Aktualisierung: 27.09.2025.",
    "Public Domain Mark",
    "[https://creativecommons.org/public-domain/pdm/](https://creativecommons.org/public-domain/pdm/)",
    "2025-09-27 18:17:02"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview (92209_3)")
```
