---
title: "Privatbesitz an Boden und Wohnraum in Basel, 2021"
subtitle: Plot and Data Preview
date-modified: 2025-09-26
volume: "Baur, Esther; Gafner, Lina (Hg.): Stadträume. Offen und begrenzt, gestaltet und umkämpft. Basel 2025 (Stadt.Geschichte.Basel 9)."
vol_short: "Stadt.Geschichte.Basel 9"
plotid: "abb92792"
format:
  html:
    fig-width: 8
    title-block-categories: false
fig-cap-location: top
---

```{r setup, include=FALSE}
#| echo: false
#| message: false
# only source the first_section of the plot script that actually generates the plot
# Packages -------------------

library(here)
library(ggplot2)
library(tidyr)
library(scales)
library(dplyr)

# Functions ------------------

source(here("src", "Funktionen", "Format_Theme.R"))
source(here("src", "Funktionen", "Format_Tausendertrennzeichen.R"))
source(here("src", "Funktionen", "Format_Achsenbeschriftung.R"))
source(here("src", "Funktionen", "Export_Plot.R"))
source(here("src", "Funktionen", "Write_InfoPage.R"))

# Read Data ------------------

source(here("src", "92792", "92792_clean.R"))

# Plot -----------------------

plot92792 <- ggplot(data92792, aes(x = `Anzahl Wohnungen`,
                                   y = reorder(Eigentümer, `Anzahl Wohnungen`))) +
  
  geom_bar(stat = "identity",
           aes(fill = "Anzahl Wohnungen")) +
  
  scale_x_continuous(
    limits = c(0, 3001.5),
    breaks = seq(0, 3000, 500),
    expand = expansion(mult = c(0, 0)),
    labels = ch_numbers
  ) +
  
  scale_fill_manual(
    values = c("Anzahl Wohnungen" = "#3f7653")) + # Bandfarbe 9

  coord_cartesian(clip = "off") +
  
  theme_sgb_basis() +
  theme(
    panel.grid.major.x = element_line(color = "black", linewidth = 0.14),
    panel.grid.major.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(margin = margin(r = 5),
                               hjust = 1),
    plot.margin = margin(0.1,1.15,0,0.4, "lines"),
    legend.position = "none",
    legend.key.width = unit(5, "mm"), # resultiert in 4.5 mm
    legend.key.height = unit(2.5, "mm"), # resultiert in 2 mm
    )

```

```{r plot_object}
#| echo: false
#| message: false
#| warning: false
#| column: page-right
#| fig-cap: "Preview only. Refer to the Research Data Platform for full metadata and production-ready files."
plot92792 + theme(legend.position = "right")
```

```{r table, results="asis"}
#| echo: false
#| message: false

library(knitr)

df <- data.frame(
  Key = c(
    "Figure",
    "Title",
    "Description",
    "Publisher",
    "Date",
    "Coverage",
    "is Part of",
    "Source (Dataset)",
    "Metadata (Dataset)",
    "Citation (Dataset)",
    "Modified"
  ),
  Value = c(
    "[abb92792](https://forschung.stadtgeschichtebasel.ch/items/abb92792.html)",
    "Privatbesitz an Boden und Wohnraum in Basel, 2021",
    "Wem gehört Basel heute? Die Darstellung zeigt die grössten Privatplayer auf dem baselstädtischen Boden- und Wohnungsmarkt. Nach einer Recherche von reflect.ch und Bajour aus dem Jahr 2021 gehört rund ein Drittel aller Wohnungen in Basel-Stadt mittlerweile institutionellen, renditeorientierten Unternehmen. Dem Staat gehörten 2016 etwa 24 Prozent der bebau-baren Kantonsfläche (Berechnung der Initiant:innen der kantonalen ‹Neuen Bodeninitiative› von 2016).",
    "[Stadt.Geschichte.Basel](https://www.wikidata.org/wiki/Q122442230)",
    "2021",
    "21. Jahrhundert",
    "Baur, Esther; Gafner, Lina (Hg.): Stadträume. Offen und begrenzt, gestaltet und umkämpft. Basel 2025 ([Stadt.Geschichte.Basel 9](https://doi.org/10.21255/sgb-09-486500)).",
    "https://reflekt.ch/recherchen/wem-gehoert-basel. Bearbeitung: Nico Görlich / Moritz Twente",
    "[data/clean/Band9/92792/92792_3_Data.csv-metadata.json](/data/clean/Band9/92792/92792_3_Data.csv-metadata.json)",
    "Stadt.Geschichte.Basel: Privatbesitz an Boden und Wohnraum in Basel, 2021. Forschungsdatenplattform Stadt.Geschichte.Basel, <https://forschung.stadtgeschichtebasel.ch/items/abb92792.html#m92792_3>, letzte Aktualisierung: 26.09.2025.",
    "2025-09-26 21:43:27"
  ),
  stringsAsFactors = FALSE
)

knitr::kable(df, format = "markdown", caption = "Dataset Overview")
```
