---
title: Workflow
subtitle: Repository Structure, Software and Data Model
lang: en
format: html
author:
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date-modified: last-modified
bibliography: references.bib
other-links:
  - text: RDM Documentation
    icon: journal-code
    href: 'https://dokumentation.stadtgeschichtebasel.ch/'
code-links:
  - href: 'https://github.com/Stadt-Geschichte-Basel/'
    text: Stadt.Geschichte.Basel
    icon: github
---

This repository stores data and R code used by the [Team for Research Data Management and Public History](https://dokumentation.stadtgeschichtebasel.ch/team.html) of the Stadt.Geschichte.Basel research project to create figures published in the [nine-volume book series](https://stadtgeschichtebasel.ch/baende).

To support open research with FAIR data, the RDM team developed a [research data platform](https://forschung.stadtgeschichtebasel.ch) [@mahrStadtGeschichteBaselResearchData2024] to ensure open, long-term access to sources and research data regarding the history of Basel. The platform facilitates access to the data behind the publication, with metadata annotation following the [Manual for Creating Non-Discriminatory Metadata for Historical Sources and Research Data](https://maehr.github.io/diskriminierungsfreie-metadaten/) [@maehrHandbuchZurErstellung2024a].

Using raw data provided by the individual authors of Stadt.Geschichte.Basel, the RDM team created maps, diagrams, and other types of visualisations for publication in the [print](https://www.merianverlag.ch/buecher/stadt.geschichte.basel.html) and [online (OA)](https://emono.unibas.ch/stadtgeschichtebasel) versions of the book series [@mahr2022d]. This repository stores code and data for charts and diagrams (referred to as plots or figures) only. For other types of data visualization in the context of Stadt.Geschichte.Basel, refer to the extensive [RDM Documentation](https://dokumentation.stadtgeschichtebasel.ch).

## Visualization Workflow

The starting point for each plot is data the authors of Stadt.Geschichte.Basel provided to the RDM team. Using R (cf. section [Software](#software)), we tidy the data, assemble multiple sources into one dataset to use for visualization, write that data to a `csv` file and store information on the dataset in an accompanying `json` metadata file structured according to the W3C standard for tabular data and metadata on the web [@w3cModelTabularData2022].

Data stewards in Stadt.Geschichte.Basel's RDM team then create visualizations for the book series, often in multiple iterations and in close cooperation with the researchers (@fig-workflow).

```{mermaid}
%%| label: fig-workflow
%%| fig-cap: The workflow comprises several iterations with a range of actors [@twenteNavigatingDisconcertmentMapMaking2025; @muenchKartenAlsBoundary2023].
 
flowchart LR
    A(Author) -->|Request| B(RDM Team)
    B -->|Drafts| A

    B -->|"Illustration (pdf)"| C(Typesetter)
    C ---> D("Printed<br>Book Series")

    B --->|"Illustration (pdf)"| E("Open Research<br>Data Platform")
    B --->|"Dataset<br>(csv, geojson)"| E
    B --->|Metadata| E

    B --->|"Code (R)"| F(sgb-figures)
    B --->|"Dataset (csv)"| F
    B --->|"Metadata (json)"| F

    F <-.-> E

    style B fill:#3a1e3e,color:#fff,stroke:#3a1e3e
    style D fill:#86bbd8,stroke:#86bbd8
    style E fill:#86bbd8,stroke:#86bbd8
    style F fill:#ffe880

    click B href "https://dokumentation.stadtgeschichtebasel.ch/team.html" "Research Data Management Team"
    click D href "https://emono.unibas.ch/stadtgeschichtebasel/" "Open Access Version"
    click E href "https://forschung.stadtgeschichtebasel.ch/" "Research Data Platform"
    click F href "https://github.com/stadt-geschichte-basel/sgb-figures/" "sgb-figures GitHub Repository"
```

While the generated `pdf` file for each plot, the corresponding legend and the `csv` dataset file are uploaded to the Research Data Platform, the R scripts used to clean the data and generate the plot are only linked to from the figures' metadata, referring to sgb-figures on GitHub.

## Repository Structure

Datasets and R scripts to generate the plots are accessible in this repository, providing a reproducible R environment to facilitate further work with the available code. Using the [Open Research Template](https://maehr.github.io/open-research-data-template/), research data is managed implementing best practices as outlined in [The&nbsp;Turing Way](https://book.the-turing-way.org/). This structured approach includes automated release management, integrated archiving with Zenodo, structured documentation via Quarto, and long-term accessibility through GitHub Pages.

R scripts, built plots, processed data and metadata files are sorted according to the following folder structure:

- `build/` – helper scripts used to build the plots
- `data/` – data files
- `docs/` – documentation for the data and the repository
- `output/` – generated PDF files
- `src/` – source code for data processing and building plots

::: {.callout-tip title="Full Repository Folder Structure Overview" icon="false" collapse="true"}
```
sgb-figures/                        
├── .devcontainer            <- GitHub Codespace settings
│   └── devcontainer.json
├── .github
│   └── workflows/
│       └── *.yaml           <- GitHub workflow settings
├── assets                   <- images, background data etc.
├── build                    <- helper scripts to build plots
├── data
│   └── clean/
│       └── <volID>/
│           └── <mediaID>
|               └── *.csv    <- dataset file
|               └── *.json   <- metadata file
├── data
│   └── raw/
│       └── <volID>/
│           └── <mediaID>/
|               └── *.xlsx   <- raw data file
├── docs                     <- project documentation
│   └── plots/
│       └── *.qmd            <- plot and data summary
│   └── plots.qmd            <- list of all plots
│   └── workflow.qmd         <- workflow and data model description
├── output
│   └── <volID>/
│       └── <mediaID>/
│           └── *.pdf        <- built plot files
├── renv                     <- R package library
├── src                      
│   └── <mediaID>/           <- source files
├── _quarto.yml              <- Quarto project settings 
├── .gitignore               <- files excluded from git version control
├── .prettierrc              <- linting settings
├── CHANGELOG.md             <- list of changes
├── CITATION.cff             <- citation specification
├── CODE_OF_CONDUCT.md       <- Code of Conduct for community projects
├── CONTRIBUTING.md          <- Contribution guideline for collaborators
├── index.qmd                <- .qmd file including README.md for Quarto
├── LICENSE-*.md             <- software and data licenses
├── package-lock.json        <- representation of the dependency tree
├── package.json             <- npm package definition and scripts
├── README.md                <- information about the repo
├── renv.lock                <- R environment settings
├── SECURITY.md              <- security policy
├── sgb-figures.Rproj        <- R project root
├── styles.css               <- R project root
└── ...                      <- other files
```
:::

- overview: what files does one plot actually consist of

Each dataset is associated with a specific plot and is accompanied by a detailed metadata file. Here's a breakdown of the data model based on the files in the repository:

-   **Data Storage**: The data is stored in CSV format. Each plot or figure has its own corresponding data file. These files are organized into directories based on the volume and figure number from the "Stadt.Geschichte.Basel" book series. For example, `data/clean/Band2/34278/34278_Data.csv`.

-   **Metadata**: Each CSV file is paired with a JSON metadata file that conforms to the [W3C CSV on the Web (CSVW)](https://www.w3.org/ns/csvw) standard. This file describes the schema of the CSV file, including column names, data types, and descriptions, as well as providing rich contextual metadata about the dataset.

## Data Model

-   **Example Schema**: Let's look at the schema for `39017_Data.csv`, which is about Ludwig Kilchmann's annuity business. The data contains the following columns:
    -   `Jahr`: The year (numeric).
    -   `Summe Ablösungen`: The total sum of redeemed annuities in that year, in Gulden (numeric).
    -   `Summe Neueinträge`: The total sum of new annuities in that year, in Gulden (numeric).
    -   `Investierte Summe netto`: The net invested sum in annuities for that year, in Gulden (numeric).

## Plot Design Principles

-   colours

## Build Workflow

```{mermaid}
%%| label: fig-scripts
%%| fig-cap: tbd.

graph LR
    subgraph User Interaction
        A[User runs 'npm run plot <ID>']
    end

    subgraph Build Process
        B{plot_pipeline.R}
        C{Finds R script in 'src/<ID>/'}
        D[Executes '<ID>_plot.R']
    end

    subgraph Data and Source
        E[Reads data from 'data/clean/<Band>/<ID>/']
        F[Generates plot using ggplot2 and other R packages]
    end

    subgraph Output
        G[Saves plot as PDF in 'output/']
    end

    A --> B;
    B --> C;
    C --> D;
    D --> E;
    D --> F;
    F --> G;
```


this produces at least one `pdf` file (two files, in most cases: the actual plot and a separate `pdf` file for its legend).

* explain script content and what is happening at what point [@fig-scripts]

Users can take advantage of a range of [npm scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts) to make it easier to build the plots directly from the command line. Running `npm run list` will generate a list of all available plots with a corresponding media ID. Using this ID, the plot, metadata and a `qmd` file containing a plot preview and data summary can be rendered using `npm run plot <ID>`. A full list of all available npm scripts is available in the [README](/index.qmd#build).

### Software {#software}

All plots are produced using [R](https://www.r-project.org/). The R environment including all necessary packages can be restored with the `renv.lock` file. In addition to [ggplot2](https://ggplot2.tidyverse.org/) and other parts of the [tidyverse](https://www.tidyverse.org/), this project uses several packages for data processing and visualization, including [here](https://here.r-lib.org/index.html) and [renv](https://rstudio.github.io/renv/index.html) for creating a [reproducible environment](https://book.the-turing-way.org/reproducible-research/renv/) as well as [csvwr](https://cloud.r-project.org/web/packages/csvwr/index.html) for writing metadata files.

Code, data and documentation are checked into [version control](https://book.the-turing-way.org/reproducible-research/vcs/) and stored in a [GitHub](https://github.com) repository using the [Open Research Data Template](https://maehr.github.io/open-research-data-template) [@mahrOneTemplateRule2025]. The documentation is rendered with [Quarto](https://quarto.org) and hosted on [GitHub Pages](https://pages.github.com).